#!/home/Python_3_Stable_Version/DataPython3.9.6/bin/python3.9
import sys
from lib2to3.main import main

sys.exit(main("lib2to3.fixes"))
